// Ashibalt — OpenAI-compatible provider (https://api.ashibalt.ru/v1).
// Chat-completions format, API-key auth (Bearer). Models fetched live from
// /v1/models (also hardcoded below as of 2026-07-02). Served by DefaultExecutor.
export default {
  id: "ashibalt",
  priority: 60,
  alias: "ash",
  aliases: ["ashibalt"],
  uiAlias: "ash",
  display: {
    name: "Ashibalt",
    icon: "bolt",
    color: "#7C3AED",
    textIcon: "AS",
    website: "https://ashibalt.ru",
    notice: {
      apiKeyUrl: "https://ashibalt.ru",
    },
  },
  category: "apikey",
  authType: "apikey",
  transport: {
    baseUrl: "https://api.ashibalt.ru/v1/chat/completions",
    validateUrl: "https://api.ashibalt.ru/v1/models",
  },
  models: [
    { id: "claude-haiku-4-5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-8", name: "Claude Opus 4.8" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-5", name: "Claude Sonnet 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "devstral-2512", name: "Devstral 2512" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash" },
    { id: "gemini-3.1-flash-lite", name: "Gemini 3.1 flash-lite" },
    { id: "gemini-3.1-pro-high", name: "Gemini 3.1 pro-high" },
    { id: "gemini-3.1-pro-low", name: "Gemini 3.1 pro-low" },
    { id: "gemini-3.5-flash-high", name: "Gemini 3.5 flash-high" },
    { id: "gemini-3.5-flash-low", name: "Gemini 3.5 flash-low" },
    { id: "gemini-3.5-flash-medium", name: "Gemini 3.5 flash-medium" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5.2", name: "GLM 5.2" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "minimax-m2.7", name: "Minimax M2.7" },
    { id: "minimax-m3", name: "Minimax M3" },
    { id: "ministral-3b-2512", name: "Ministral 3b-2512" },
    { id: "ministral-8b-2512", name: "Ministral 8b-2512" },
    { id: "mistral-large-2512", name: "Mistral large-2512" },
    { id: "mistral-medium-2505", name: "Mistral Medium-2505" },
    { id: "mistral-medium-2508", name: "Mistral Medium-2508" },
    { id: "mistral-medium-3.5", name: "Mistral Medium-3.5" },
    { id: "mistral-small-2506", name: "Mistral Small-2506" },
    { id: "mistral-small-4-119b-2603", name: "Mistral Small-4-119b-2603" },
    { id: "nemotron-3-ultra-nvfp4", name: "NVIDIA Nemotron 3 Ultra NVFP4" },
    { id: "qwen3.5-397b-a17b", name: "Qwen3.5 397B A17b" },
    { id: "qwen3.5-flash", name: "Qwen3.5 Flash" },
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "qwen3.6-flash", name: "Qwen3.6 Flash" },
    { id: "qwen3.6-max-preview", name: "Qwen3.6 Max Preview" },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "step-3.5-flash", name: "Step 3.5 flash" },
    { id: "step-3.7-flash", name: "Step 3.7 flash" },
  ],
  modelsFetcher: { url: "https://api.ashibalt.ru/v1/models", type: "openai" },
  serviceKinds: ["llm"],
};
